### ISSUE TITLE
I need v1.6.4.Can you post this version?

### ISSUE THREAD

**Issue by jidalzxz** [Royalgamer06/SteamWebIntegration#1]
Hi
1.6.5 dont work 
I need v1.6.4.Can you post this version?

**Comment by Royalgamer06** [comment]
You want https://github.com/Royalgamer06/SteamWebIntegration/blob/033b792252381f5825fb74ec4de6c27f0a0b1d2d/Steam%20Web%20Integration.user.js ?
I'm sure V1.6.4 won't work.

**Comment by jidalzxz** [comment]
shows only one game
https://ibb.co/iLLyDG

**Comment by jidalzxz** [comment]
and 1.6.3 will work? Can it try?

**Comment by Royalgamer06** [comment]
You can see all versions here: https://github.com/Royalgamer06/SteamWebIntegration/commits/master/Steam%20Web%20Integration.user.js
