### ISSUE TITLE
How to use it? 

### ISSUE THREAD

**Issue by AndrewRAN** [Royalgamer06/SteamWebIntegration#2]
Hi, I'm retarded a bit. Can you tell me how to use it?

**Comment by Royalgamer06** [comment]
1. https://tampermonkey.net
2. https://github.com/Royalgamer06/SteamWebIntegration/raw/master/Steam%20Web%20Integration.user.js

**Comment by AndrewRAN** [comment]
I downloaded it already.

**Comment by AndrewRAN** [comment]
I'm retarded *a bit*.

**Comment by AndrewRAN** [comment]
Yeah, TY for help <3
