### ISSUE TITLE
It doesnt work

### ISSUE THREAD

**Issue by BreeL-GH** [Royalgamer06/SteamWebIntegration#3]
I have last version of this script and last version of chrome and tampermonkey
Idk why its not work

**Comment by BreeL-GH** [comment]
Here is console log
https://prnt.sc/hcj0g0

**Comment by Luckz** [comment]
Make sure it's set to:
const wantCards = false;

(and yes, this is months old, but..)

**Comment by Royalgamer06** [comment]
Update now and try again. It should work.
