### ISSUE TITLE
Firefox does not show cards.

### ISSUE THREAD

**Issue by OneLastKiss** [Royalgamer06/SteamWebIntegration#5]
I'm generally using Opera browser and this script working well in there but when i use the firefox browser, i can not see situation of cards for games.

Also, most of the new games show  fake card status via steam, so SteamCardExchange is best way to learn it.

Thank you in advance.

**Comment by Luckz** [comment]
I assume you had card status indexed back when the website this data was from still allowed this.
Ergo your Opera card status is months old, and a fresh install won't be able to download it.
=> http://cdn.steam.tools/data/set_data.json has been 403 Forbidden for quite some time.

**Comment by Royalgamer06** [comment]
Fixed now
